### ISSUE TITLE
Could not find a version that satisfies the requirement oathtool - raspberry pi

### ISSUE THREAD

**Issue by matt199x** [jaraco/oathtool#1]
`pip install oathtool
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting oathtool
Could not find a version that satisfies the requirement oathtool (from versions: )
No matching distribution found for oathtool`

**Comment by jaraco** [comment]
My guess is you're using Python 2.7, which was released in 2010 and sunset in 2020. Just use Python 3.

**Comment by jaraco** [comment]
On further consideration, it sort-of appears as if the v1.0 release did intend to support Python 2. Maybe that can be made so.

**Comment by jaraco** [comment]
After reviewing, Python 2 was never supported. There aren't tests and when I tried using the library on Python 2, it fails with errors. Therefore, it'll require a backport to Python 2.7, something I doubt is worth the trouble. If someone is interested in investing the time, I'll support it.
